sudo: required
dist: xenial

os:
  - linux
  - osx
  - windows

language: go
go:
  - 1.x

matrix:
  include:
    - os: osx
      before_install:
        - GO111MODULE=on go get github.com/ipfs/ipfs-update
        - ipfs-update install v0.4.21
      install:
        - go get -d -t -v ./...
        - go test ./...
        - go build
    - os: linux
      before_install:
        - GO111MODULE=on go get github.com/ipfs/ipfs-update
        - ipfs-update install v0.4.21
      install:
        - go get -d -t -v ./...
        - go test ./...
        - go build
    - os: windows
      before_install:
        - GO111MODULE=on go get github.com/ipfs/ipfs-update
        - ipfs-update install v0.4.21
      install:
        - go get -d -t -v ./...
        - go test ./...
        - go build
