sudo: required
dist: xenial

os:
  - linux
  - osx
  - windows

language: go
go:
  - 1.x

matrix:
  include:
    - os: osx
      install:
        - go get -d -t -v ./...
        - go test ./...
        - go build
    - os: linux
      install:
        - go get -d -t -v ./...
        - go test ./...
        - go build
    - os: windows
      install:
        - go get -d -t -v ./...
        - go test ./...
        - go build
