sudo: required
dist: xenial

os:
  - linux
  - osx
  - windows

language: go
go:
  - 1.14.x

before_install:
  - GO111MODULE=on go get github.com/ipfs/ipfs-update
  - ipfs-update install v0.4.21

script:
  - go get -d -t -v ./...
  - go test ./...
  - go build
