sudo: required
dist: xenial

os:
  - linux
  - osx
  - windows

language: go
go:
  - 1.x

matrix:
  include:
    - os: osx
      install:
        - go get -d -t -v ./...
        - go test ./...
        - go build
    - os: linux
      before_install:
        - mkdir temp && curl https://dist.ipfs.io/go-ipfs/v0.4.23/go-ipfs_v0.4.23_linux-amd64.tar.gz | tar xzC temp && cd temp && cd *
        - sudo ./install.sh
      install:
        - go get -d -t -v ./...
        - go test ./...
        - go build
    - os: windows
      install:
        - go get -d -t -v ./...
        - go test ./...
        - go build
