site_name: scribe-docs
repo_url: https://github.com/will-rowe/scribe
site_author: Will Rowe
nav:
  - Home: index.md
  - Installation: installation.md
  - Quick start: quick-start.md
theme: readthedocs
